# Dockerfile.streamlit
FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

ENV PYTHONPATH=/app/src

EXPOSE 8501

CMD ["streamlit", "run", "app/streamlitapp.py", "--server.address=0.0.0.0", "--server.port=8501"]
