stages:
  train:
    cmd: python -m fraud.training.run_train
    deps:
      - src/fraud/training/train.py
      - src/fraud/training/run_train.py
      - src/fraud/features/
      - src/fraud/data/load_data.py
      - dataset/merged_data_pruned.parquet
    outs:
      - artifacts/featurizer.joblib
      - artifacts/train_meta.joblib
      - models/xgb_model.joblib
